apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
  namespace: ase-ns-13
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: 'zfhub/lab4_frontend:v1.12'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: frontend
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
