apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: order
  namespace: ase-ns-13
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: order
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: order
    spec:
      initContainers:
      - image: zfhub/skywalking-agent:8.8.0-1
        name: skywalking-agent
        imagePullPolicy: IfNotPresent
        command: ['sh']
        args: ['-c','mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent']
        volumeMounts:
        - mountPath: /skywalking/agent
          name: sw-agent
      containers:
      - name: order
        image: 'zfhub/lab4_order:v1.3'
        imagePullPolicy: IfNotPresent
        command:
          - java
          - '-javaagent:/usr/skywalking/agent/skywalking-agent.jar'
          - '-Dskywalking.agent.service_name=order'
          - '-jar'
          - /app/app.jar
        env:
          - name: JAVA_OPTS
            value: -javaagent:/usr/skywalking/agent/skywalking-agent.jar
          - name: SW_AGENT_NAME
            value: order
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: oap:11800
        ports:
          - containerPort: 6784
            protocol: TCP
        volumeMounts:
        - mountPath: /usr/skywalking/agent
          name: sw-agent
        resources:
          limits:
            memory: 1Gi
            cpu: 800m
          requests:
            memory: 1Gi
            cpu: 800m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: sw-agent
        emptyDir: {}
      dnsPolicy: ClusterFirst
      hostname: order
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
