apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rabbitmq
  namespace: ase-ns-13
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: 'rabbitmq:3.9.10-management'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5672
            protocol: TCP
          - containerPort: 15672
            protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: admin
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: rabbitmq
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
