apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
  namespace: ase-ns-13
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: 'zfhub/lab4_redis:v1.0'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
            protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: redis
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
