apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ase-ns-13
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
