apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ase-ns-13
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
  - name: prometheus-web
    port: 9090
    targetPort: 9090
