apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: account
  namespace: ase-ns-13
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 60   ## cpu的限制在60%
        type: Utilization
