apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ase-ns-13
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: frontend
  type: LoadBalancer
  
