apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ase-ns-13
spec:
  ports:
  - port: 6786
    targetPort: 6786
    protocol: TCP
  selector:
    name: gateway
  type: LoadBalancer
  
