apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ase-ns-13
spec:
  ports:
  - port: 6785
    targetPort: 6785
    nodePort: 32147
    protocol: TCP
  selector:
    name: gateway
  type: LoadBalancer
  
