apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: account
  name: account
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 6782
      protocol: TCP
      targetPort: 6782
  selector:
    name: account
  sessionAffinity: None
  type: ClusterIP
