apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: commodity
  name: commodity
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 6788
      protocol: TCP
      targetPort: 6788
  selector:
    name: commodity
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
