apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: frontend
  name: frontend
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 1024
      protocol: TCP
      targetPort: 80
  selector:
    name: frontend
  sessionAffinity: None
  type: ClusterIP
