apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mysql
  name: mysql
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
