apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: notification
  name: notification
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 6785
      protocol: TCP
      targetPort: 6785
  selector:
    name: notification
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
