apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: rabbitmq
  name: rabbitmq
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: p2
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    name: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
