apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: redis
  name: redis
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
