apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: shoppingcart
  name: shopping-cart
  namespace: ase-ns-13
spec:
  clusterIP: None
  ports:
    - name: p1
      port: 6783
      protocol: TCP
      targetPort: 6783
  selector:
    name: shoppingcart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
